In [44]:
print("Hello Earth")

Hello Earth


In [45]:
var_int = 8
var_float = 15.0
var_scifloat = 4e8
var_complex = complex(4, 2)
var_greetings = 'Hello Earth'

In [46]:
 type(var_int),  type(var_float), type(var_scifloat), type(var_complex), type(var_greetings)

(int, float, float, complex, str)

In [47]:
var_float/var_int

1.875

In [48]:
int(var_float/var_int)

1

In [42]:
var_string = '815'
int(var_string)

10

In [50]:
add_sub = 8+15-42
mult_div_exp = (8*15/42)**4
print(add_sub, mult_div_exp)

-19 66.63890045814244


In [51]:
div_quo = 15 // 8
div_mod = 15 % 8
print(div_quo, div_mod)

1 7


In [19]:
round(mult_div_exp), abs(add_sub)

NameError: name 'mult_div_exp' is not defined

In [20]:
mixed_list = [8, 15, "Oceanic"]
mixed_list

[8, 15, 'Oceanic']

In [21]:
mixed_list[0], mixed_list[2]

(8, 'Oceanic')

In [22]:
mixed_list.append("Flight")
mixed_list

[8, 15, 'Oceanic', 'Flight']

In [50]:
numbers_list = [4, 8, 15, 16, 23, 42]
print(numbers_list*2)

[4, 8, 15, 16, 23, 42, 4, 8, 15, 16, 23, 42]


In [53]:
numbers_list + cool_list

[4, 8, 15, 16, 23, 42, 8, 15, 'Oceanic', 'Flight']

In [9]:
double_list=[]
for item in numbers_list:
    double_list.append(item*2)
double_list

[8, 16, 30, 32, 46, 84]

In [57]:
import numpy as np

In [59]:
numbers_array = np.array(numbers_list)
numbers_array*2

array([ 8, 16, 30, 32, 46, 84])

In [59]:
numbers_array[0]

4

In [60]:
np.sort(numbers_array)

array([ 4,  8, 15, 16, 23, 42])

In [61]:
numbers_array_2d = numbers_array.reshape(2,3)
numbers_array_2d

array([[ 4,  8, 15],
       [16, 23, 42]])

In [62]:
numbers_array_2d[1,1]

23

In [63]:
np.zeros(10), np.full(10, np.nan), np.arange(0, 5, 0.5)

(array([ 0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.]),
 array([ nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan,  nan]),
 array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5]))

In [61]:
masked_nums = (numbers_array > 8)
masked_nums

array([False, False,  True,  True,  True,  True], dtype=bool)

In [62]:
numbers_array[masked_nums]

array([15, 16, 23, 42])

In [64]:
numbers_mask_array = np.ma.array(numbers_array, mask=~masked_nums)
numbers_mask_array, numbers_array.size

(masked_array(data = [-- -- 15 16 23 42],
              mask = [ True  True False False False False],
        fill_value = 999999), 6)

In [67]:
numbers_array.min(), numbers_array.max()

(4, 42)

In [68]:
from datetime import datetime, timedelta

In [69]:
 #September 22, 2004 at 4:16 P.M
flight_time = datetime(2004, 9, 22, 4, 16)
flight_time.isoformat()

'2004-09-22T04:16:00'

In [70]:
flight_time.isoformat(), flight_time.strftime('%Y/%m/%d %H:%m')

('2004-09-22T04:16:00', '2004/09/22 04:09')

In [71]:
flight_time_shift = flight_time+timedelta(days=101)
flight_time_shift.strftime('%h %d %Y')

'Jan 01 2005'

In [65]:
team_members = ['Sayid', 'Claire', 'Jack', 'Hurley', 'Sawyer',
    'Sun-Hwa', 'Kate', 'Charlie', 'Locke', 'Desmond', 'Juliet'
    ]

for member in team_members:
    print(member)

Sayid
Claire
Jack
Hurley
Sawyer
Sun-Hwa
Kate
Charlie
Locke
Desmond
Juliet


In [115]:
for member in team_members:
    if member[0] == 'J':
        print(member)

Jack
Juliet


In [116]:
exp_numbers=[]
for i in np.arange(0, 11):
    exp_numbers.append(i**2)
print(exp_numbers)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [118]:
for i, exp_number in enumerate(exp_numbers):
    print(i, exp_number)

0 0
1 1
2 4
3 9
4 16
5 25
6 36
7 49
8 64
9 81
10 100


In [119]:
div_by_5 = False
i = 0

while not div_by_5:
    num = exp_numbers[i]
    
    if num == 0:
        i=i+1
        continue
    
    if (num%5 == 0):
        print(num)
        div_by_5 = True
    else:
        i=i+1
        if i >= len(exp_numbers):
            div_by_5 = True
            break

25


In [120]:
[member for member in team_members if member[0] == 'J']

['Jack', 'Juliet']

In [67]:
exp_numbers_list = [value**2 for value in np.arange(0,11)]
print(exp_numbers_list)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [68]:
 list(np.arange(0,11)**2)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [122]:
filtered_values = [value for value in exp_numbers_list if (value%5 == 0) 
   & (value > 0)]
print(filtered_values[0])

25
