## 4.1 "Hello Earth" in Python

In [1]:
print("Hello Earth")

Hello Earth


## 4.2 Variable Assigningment and Arithmetic

In [2]:
var_int = 8
var_float = 15.0
var_scifloat = 4e8
var_complex = complex(4, 2)
var_greetings = 'Hello Earth'

In [3]:
 type(var_int),  type(var_float), type(var_scifloat), type(var_complex), type(var_greetings)

(int, float, float, complex, str)

In [4]:
var_float/var_int

1.875

In [5]:
int(var_float/var_int)

1

In [6]:
var_string = '815'
int(var_string)

815

In [7]:
add_sub = 8+15-42
mult_div_exp = (8*15/42)**4
print(add_sub, mult_div_exp)

-19 66.63890045814244


In [8]:
div_quo = 15 // 8
div_mod = 15 % 8
print(div_quo, div_mod)

1 7


In [9]:
abs(add_sub), round(mult_div_exp)

(19, 67)

## 4.3 Lists

In [10]:
mixed_list = [8, 15, "Oceanic"]
mixed_list

[8, 15, 'Oceanic']

In [11]:
mixed_list[0], mixed_list[2]

(8, 'Oceanic')

In [12]:
mixed_list.append("Flight")
mixed_list

[8, 15, 'Oceanic', 'Flight']

In [13]:
numbers_list = [4, 8, 15, 16, 23, 42]
print(numbers_list*2)

[4, 8, 15, 16, 23, 42, 4, 8, 15, 16, 23, 42]


In [14]:
numbers_list + mixed_list

[4, 8, 15, 16, 23, 42, 8, 15, 'Oceanic', 'Flight']

## 4.4 Importing Packages

In [15]:
import numpy as np

## 4.5 Array and Matrix Operations

In [16]:
numbers_array = np.array(numbers_list)
numbers_array*2

array([ 8, 16, 30, 32, 46, 84])

In [17]:
numbers_array[0]

4

In [18]:
np.sort(numbers_array)

array([ 4,  8, 15, 16, 23, 42])

In [19]:
numbers_array_2d = numbers_array.reshape(2,3)
numbers_array_2d

array([[ 4,  8, 15],
       [16, 23, 42]])

In [20]:
numbers_array_2d[1,1]

23

In [21]:
np.zeros(10), np.full(10, np.nan), np.arange(0, 5, 0.5)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([nan, nan, nan, nan, nan, nan, nan, nan, nan, nan]),
 array([0. , 0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5]))

In [22]:
masked_nums = (numbers_array > 8)
masked_nums

array([False, False,  True,  True,  True,  True])

In [54]:
masked_nums_and = (numbers_array > 8) & (numbers_array < 30)
masked_nums_and

array([False, False,  True,  True,  True, False])

In [55]:
masked_nums_or = (numbers_array < 8) | (numbers_array > 30)
masked_nums_or

array([ True, False, False, False, False,  True])

In [25]:
numbers_array[masked_nums]

array([ 4, 42])

In [26]:
numbers_mask_array = np.ma.array(numbers_array, mask=~masked_nums)
numbers_mask_array, numbers_array.size

(masked_array(data=[4, --, --, --, --, 42],
              mask=[False,  True,  True,  True,  True, False],
        fill_value=999999),
 6)

In [27]:
numbers_array.min(), numbers_array.max()

(4, 42)

## 4.6 Time Series Data

In [28]:
from datetime import datetime, timedelta

In [29]:
 #September 22, 2004 at 4:16 P.M
flight_time = datetime(2004, 9, 22, 4, 16)
flight_time.isoformat()

'2004-09-22T04:16:00'

In [30]:
flight_time.isoformat(), flight_time.strftime('%Y/%m/%d %H:%m')

('2004-09-22T04:16:00', '2004/09/22 04:09')

In [31]:
flight_time_shift = flight_time+timedelta(days=101)
flight_time_shift.strftime('%h %d %Y')

'Jan 01 2005'

## 4.7 Loops

In [32]:
team_members = ['Sayid', 'Claire', 'Jack', 'Hurley', 'Sawyer',
    'Sun-Hwa', 'Kate', 'Charlie', 'Locke', 'Desmond', 'Juliet'
    ]

for member in team_members:
    print(member)

Sayid
Claire
Jack
Hurley
Sawyer
Sun-Hwa
Kate
Charlie
Locke
Desmond
Juliet


In [33]:
for member in team_members:
    if member[0] == 'J':
        print(member)

Jack
Juliet


In [34]:
exp_numbers=[]
for i in np.arange(0, 11):
    exp_numbers.append(i**2)
print(exp_numbers)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [35]:
for i, exp_number in enumerate(exp_numbers):
    print(i, exp_number)

0 0
1 1
2 4
3 9
4 16
5 25
6 36
7 49
8 64
9 81
10 100


In [36]:
div_by_5 = False
i = 0

while not div_by_5:
    num = exp_numbers[i]
    
    if num == 0:
        i=i+1
        continue
    
    if (num%5 == 0):
        print(num)
        div_by_5 = True
    else:
        i=i+1
        if i >= len(exp_numbers):
            div_by_5 = True
            break

25


## 4.8 List Comprehensions

In [37]:
[member for member in team_members if member[0] == 'J']

['Jack', 'Juliet']

In [38]:
exp_numbers_list = [value**2 for value in np.arange(0,11)]
print(exp_numbers_list)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


In [39]:
 list(np.arange(0,11)**2)

[0, 1, 4, 9, 16, 25, 36, 49, 64, 81, 100]

In [40]:
filtered_values = [value for value in exp_numbers_list if (value%5 == 0) 
   & (value > 0)]
print(filtered_values[0])

25


## 4.9 Functions

In [41]:
def hello_earth():
    print("Hello Earth")

In [42]:
hello_earth()

Hello Earth


In [43]:
def celsius_to_fahrenheit(Tc):
    """This function will take a temperature in Celsius and convert to Fahrenheit.

    Arguments:
        Tc: Temperature in Celsius

    Returns:
        Tf: Temperature in Fahrenheit
    """
    Tf = Tc*(9/5)+32
    return Tf

In [44]:
temp_f = celsius_to_fahrenheit(40)
print(temp_f)

104.0


In [45]:
def convert_temp(T=-999, convert_to='C'):
    '''This function will take a temperature in Celsius and convert to Fahrenheit.

    Arguments:
        T : Temperature in Celsius or Farenheit
        convert_to: conversion to 

    Returns:
        Tout: Temperature in Fahrenheit, Celsius, or -999 if nothing is calculated
    '''
    
    if convert_to == 'C':
        Tout = T*(9/5)+32
    elif convert_to == 'C':
        Tout = (T-32)*(5/9)
    else:
        print("Unrecognized conversion")
        Tout = -999
    return Tout

In [46]:
def daily_precip(*args):
    '''This function calculates total rainfall of any number of arguments
    
    Arguments:
        hourly rain totals
    Returns:
        Total precipitation
    '''
    result = 0
    for arg in args:
        result = result + arg
    return result

In [47]:
daily_precip(12, 20, 33)

65

In [48]:
def daily_precip_list(args):
    result = 0
    for arg in args:
        result = result + arg
    return result

In [49]:
hourly_precip = [0, 12, 20, 33]
daily_precip_list(hourly_precip)

65

## 4.10 Dictionaries

In [50]:
ocean_units = {
  "temperature": "C",
  "velocity": "cm/s^2",
  "density": "kg/m^3",
  "pressure" : "dbar",
  "salinity" : "ppt"
}
ocean_units['pressure']

'dbar'

In [51]:
ocean_units.update({"salinity" : "ppt"})

In [52]:
ocean_units.items()

dict_items([('temperature', 'C'), ('velocity', 'cm/s^2'), ('density', 'kg/m^3'), ('pressure', 'dbar'), ('salinity', 'ppt')])

In [53]:
def print_units(**kwargs):
    # Prints the variable and its units in a complete sentence
    for key, value in kwargs.items():
        print("The units for " + key + " are " + value)

print_units(**ocean_units)

The units for temperature are C
The units for velocity are cm/s^2
The units for density are kg/m^3
The units for pressure are dbar
The units for salinity are ppt
