In [37]:
import numpy as np

In [74]:
trace_gases.Latitude[0:2]

0    39.693913
1    39.996113
Name: Latitude, dtype: float64

In [9]:
import pandas as pd
fname = 'data/campfire-gases-2018-11.csv'
trace_gases = pd.read_csv(fname)

In [16]:
trace_gases.head()

Latitude  Longitude     Time  H2O_MR_500mb  H2O_MR_850mb  CO_MR_500mb  \
0  39.693913 -120.49820  39:44.2      0.001621      0.008410     84.18882   
1  39.996113 -121.75796  39:44.4      0.001781      0.004849     77.59622   
2  39.248516 -120.72343  39:52.2      0.001681      0.005230     80.73684   
3  39.547660 -121.97622  39:52.4      0.001817      0.005295     77.39363   
4  38.802532 -120.94534  40:00.2      0.001604      0.004505     82.68274   

   O3_MR_500mb  CH4_MR_500mb  N2O_MR_500mb  CO2_500mb  
0    46.428890     1842.4436     318.75995  402.26596  
1    44.728848     1861.1800     318.01180  402.76318  
2    46.114296     1861.7188     319.00397  402.35360  
3    44.257423     1847.3370     318.03134  403.03867  
4    47.121635     1890.4450     319.56244  403.35144

In [58]:
trace_gases['H2O_MR_500mb']

0      0.001621
1      0.001781
2      0.001681
3      0.001817
4      0.001604
5      0.000475
6      0.000596
7      0.000552
8      0.000573
9      0.000563
10     0.000490
11     0.000473
12     0.000450
13     0.000541
14     0.000461
15     0.000438
16     0.000566
17     0.000524
18     0.000518
19     0.000519
20     0.000555
21     0.000359
22     0.000143
23     0.001352
24     0.001174
25     0.000779
26     0.000715
27     0.000804
28     0.000725
29     0.000762
         ...   
461    0.002262
462    0.000266
463    0.000590
464    0.000319
465    0.000700
466    0.000552
467    0.000573
468    0.000487
469    0.000468
470    0.000624
471    0.000309
472    0.000404
473    0.000244
474    0.000410
475    0.000402
476    0.000282
477    0.000256
478    0.000230
479    0.000439
480    0.000234
481    0.000278
482    0.000504
483    0.000540
484    0.000336
485    0.000488
486    0.000471
487    0.000466
488    0.000484
489    0.000289
490    0.000273
Name: H2O_MR_500mb, Leng

In [11]:
drops = list(trace_gases.columns[5:])
print(drops)

['CO_MR_500mb', 'O3_MR_500mb', 'CH4_MR_500mb', 'N2O_MR_500mb', 'CO2_500mb']


In [17]:
trace_gases.drop(columns=drops, inplace=True)

In [18]:
trace_gases.head()

Latitude  Longitude     Time  H2O_MR_500mb  H2O_MR_850mb
0  39.693913 -120.49820  39:44.2      0.001621      0.008410
1  39.996113 -121.75796  39:44.4      0.001781      0.004849
2  39.248516 -120.72343  39:52.2      0.001681      0.005230
3  39.547660 -121.97622  39:52.4      0.001817      0.005295
4  38.802532 -120.94534  40:00.2      0.001604      0.004505

In [12]:
with open('data/campfire-gases-2018-11.csv') as data:
    for row in data:
        print(row)
        column=''
        for character in row:
            if character != ',':
                column=column+character
            else:
                print(column)
                column = ''
        break

Latitude,Longitude,Time,H2O_MR_500mb,H2O_MR_850mb,CO_MR_500mb,O3_MR_500mb,CH4_MR_500mb,N2O_MR_500mb,CO2_500mb

Latitude
Longitude
Time
H2O_MR_500mb
H2O_MR_850mb
CO_MR_500mb
O3_MR_500mb
CH4_MR_500mb
N2O_MR_500mb


In [8]:
#This could be replaced by something like ' '.join(row.split(','))

with open('data/campfire-gases-2018-11.csv') as data:
    for row in data:
        print(row.split(','))
        break


['Latitude', 'Longitude', 'Time', 'H2O_MR_500mb', 'H2O_MR_850mb', 'CO_MR_500mb', 'CO_MR_850mb', 'O3_MR_500mb', 'O3_MR_850mb', 'CH4_MR_500mb', 'CH4_MR_850mb', 'N2O_MR_500mb', 'N2O_MR_850mb', 'CO2_500mb', 'CO2_850mb', 'Datetime\n']


In [77]:
from netCDF4 import Dataset

In [78]:
fname='data/JRR-AOD_v1r1_npp_s201808091955538_e201808091957180_c201808092049460.nc'
file_id = Dataset(fname)

In [80]:
print(file_id)

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    Conventions: CF-1.5
    Metadata_Conventions: CF-1.5, Unidata Dataset Discovery v1.0
    standard_name_vocabulary: CF Standard Name Table (version 17, 24 March 2011)
    project: S-NPP Data Exploitation
    institution: DOC/NOAA/NESDIS/NDE->S-NPP Data Exploitation, NESDIS, NOAA, U.S. Department of Commerce
    naming_authority: gov.noaa.nesdis.nde
    satellite_name: NPP
    instrument_name: VIIRS
    title: JPSS Risk Reduction Unique Aerosol Optical Depth
    summary: Aerosol Optical Depth
    history: VIIRS AOD Version 1.0
    processing_level: NOAA Level 2
    references: 
    id: 7e854908-1172-4d11-ae90-fb768144e6b2
    Metadata_Link: JRR-AOD_v1r1_npp_s201808091955538_e201808091957180_c201808092049460.nc
    start_orbit_number: 35149
    end_orbit_number: 35149
    day_night_data_flag: day
    ascend_descend_data_flag: 0
    time_coverage_start: 2018-08-09T19:55:53Z
    time_coverage_end: 2018

In [10]:
file_id.variables.keys()

odict_keys(['Latitude', 'Longitude', 'StartRow', 'StartColumn', 'AOD550', 'AOD_channel', 'AngsExp1', 'AngsExp2', 'QCPath', 'AerMdl', 'FineMdlIdx', 'CoarseMdlIdx', 'FineModWgt', 'SfcRefl', 'SpaStddev', 'Residual', 'AOD550LndMdl', 'ResLndMdl', 'MeanAOD', 'HighQualityPct', 'RetrievalPct', 'QCRet', 'QCExtn', 'QCTest', 'QCInput', 'QCAll'])

In [11]:
AOD550 = file_id.variables['AOD550']
type(AOD550)

netCDF4._netCDF4.Variable

In [12]:
import numpy as np
AOD550 = np.array(AOD550)
AOD550.shape

(768, 3200)

In [13]:
AOD550

array([[-999.99902344, -999.99902344, -999.99902344, ..., -999.99902344,
        -999.99902344, -999.99902344],
       [-999.99902344, -999.99902344, -999.99902344, ..., -999.99902344,
        -999.99902344, -999.99902344],
       [-999.99902344, -999.99902344, -999.99902344, ..., -999.99902344,
        -999.99902344, -999.99902344],
       ..., 
       [-999.99902344, -999.99902344, -999.99902344, ..., -999.99902344,
        -999.99902344, -999.99902344],
       [-999.99902344, -999.99902344, -999.99902344, ..., -999.99902344,
        -999.99902344, -999.99902344],
       [-999.99902344, -999.99902344, -999.99902344, ..., -999.99902344,
        -999.99902344, -999.99902344]], dtype=float32)

In [14]:
avgAOD = AOD550.mean()
print(avgAOD)

-289.096


In [15]:
print(file_id.variables['AOD550'])

<class 'netCDF4._netCDF4.Variable'>
float32 AOD550(Rows, Columns)
    long_name: Aerosol optical depth at 550 nm
    coordinates: Longitude Latitude
    units: 1
    _FillValue: -999.999
    valid_range: [-0.05  5.  ]
unlimited dimensions: 
current shape = (768, 3200)
filling on


In [16]:
missing = file_id.variables['AOD550']._FillValue
missing

-999.99902

In [17]:
keepRows = AOD550 != missing

AOD550[50:60, 100], keepRows[50:60, 100]

(array([ -9.99999023e+02,  -9.99999023e+02,   5.40565491e-01,
          6.31573617e-01,   1.57470262e+00,   5.97368181e-01,
          6.23970449e-01,   6.71409011e-01,   6.59592867e-01,
          7.61033893e-01], dtype=float32),
 array([False, False,  True,  True,  True,  True,  True,  True,  True,  True], dtype=bool))

In [18]:
AOD550_filtered = AOD550[keepRows]
AOD550_filtered

array([ 0.06569075,  0.08305545,  0.11872342, ...,  0.14237013,
        0.16145205,  0.14933026], dtype=float32)

In [19]:
# Re-compute the statistics, these values look more reasonable.
avgAOD = AOD550_filtered.mean()
avgAOD

0.41903266

In [20]:
AOD550.size, AOD550_filtered.size

(2457600, 1746384)

In [21]:
AOD550 = file_id.variables['AOD550'][:,:]
type(AOD550)

numpy.ma.core.MaskedArray

In [22]:
AOD550[50:60, 100]

masked_array(data = [-- -- 0.5405654907226562 0.6315736174583435 1.5747026205062866
 0.5973681807518005 0.6239704489707947 0.671409010887146 0.659592866897583
 0.7610338926315308],
             mask = [ True  True False False False False False False False False],
       fill_value = -999.999)

In [23]:
avgAOD = AOD550.mean()
avgAOD

0.41903259105672064

In [24]:
file_id.variables['AOD550'].valid_range

array([-0.05,  5.  ], dtype=float32)

In [60]:
import h5py

fname = 'data/3B-HHR.MS.MRG.3IMERG.20170827-S120000-E122959.0720.V06B.HDF5' 
file_id = h5py.File(fname, 'r')
file_id

<HDF5 file "3B-HHR.MS.MRG.3IMERG.20170827-S120000-E122959.0720.V06B.HDF5" (mode r)>

In [61]:
list(file_id)

['Grid']

In [62]:
print(list(file_id["Grid"].keys()))

['nv', 'lonv', 'latv', 'time', 'lon', 'lat', 'time_bnds', 'lon_bnds', 'lat_bnds', 'precipitationCal', 'precipitationUncal', 'randomError', 'HQprecipitation', 'HQprecipSource', 'HQobservationTime', 'IRprecipitation', 'IRkalmanFilterWeight', 'probabilityLiquidPrecipitation', 'precipitationQualityIndex']


In [64]:
file_id.visit(print)

Grid
Grid/precipitationQualityIndex
Grid/IRkalmanFilterWeight
Grid/HQprecipSource
Grid/lon
Grid/precipitationCal
Grid/time
Grid/lat_bnds
Grid/precipitationUncal
Grid/lonv
Grid/nv
Grid/lat
Grid/latv
Grid/HQprecipitation
Grid/probabilityLiquidPrecipitation
Grid/HQobservationTime
Grid/randomError
Grid/time_bnds
Grid/IRprecipitation
Grid/lon_bnds
None


In [29]:
precip = file_id["Grid/HQprecipitation"][:,:,:]
precip

array([[[-9999.90039062, -9999.90039062, -9999.90039062, ...,
         -9999.90039062, -9999.90039062, -9999.90039062],
        [-9999.90039062, -9999.90039062, -9999.90039062, ...,
         -9999.90039062, -9999.90039062, -9999.90039062],
        [-9999.90039062, -9999.90039062, -9999.90039062, ...,
         -9999.90039062, -9999.90039062, -9999.90039062],
        ..., 
        [-9999.90039062, -9999.90039062, -9999.90039062, ...,
         -9999.90039062, -9999.90039062, -9999.90039062],
        [-9999.90039062, -9999.90039062, -9999.90039062, ...,
         -9999.90039062, -9999.90039062, -9999.90039062],
        [-9999.90039062, -9999.90039062, -9999.90039062, ...,
         -9999.90039062, -9999.90039062, -9999.90039062]]], dtype=float32)

In [65]:
print(list(file_id["Grid/HQprecipitation"].attrs))

['DimensionNames', 'Units', 'units', 'coordinates', '_FillValue', 'CodeMissingValue', 'DIMENSION_LIST']


In [31]:
missing = file_id["Grid/HQprecipitation"].attrs['_FillValue']
missing

-9999.9004

In [32]:
PrecipMask = (precip == missing)
precip = np.ma.masked_array(precip, mask=PrecipMask)
precip

masked_array(data =
 [[[-- -- -- ..., -- -- --]
  [-- -- -- ..., -- -- --]
  [-- -- -- ..., -- -- --]
  ..., 
  [-- -- -- ..., -- -- --]
  [-- -- -- ..., -- -- --]
  [-- -- -- ..., -- -- --]]],
             mask =
 [[[ True  True  True ...,  True  True  True]
  [ True  True  True ...,  True  True  True]
  [ True  True  True ...,  True  True  True]
  ..., 
  [ True  True  True ...,  True  True  True]
  [ True  True  True ...,  True  True  True]
  [ True  True  True ...,  True  True  True]]],
       fill_value = 1e+20)

In [33]:
precip.mean()

0.066204481327029399

In [34]:
import xarray as xr
import numpy as np

In [35]:
fname = 'data/NUCAPS-EDR_v2r0_npp_s201903031848390_e201903031849090_c201903031941100.nc'
nucaps = xr.open_dataset(fname, decode_times=False)
nucaps

<xarray.Dataset>
Dimensions:               (Number_of_Cloud_Emis_Hing_Pts: 100, Number_of_Cloud_Layers: 8, Number_of_CrIS_FORs: 120, Number_of_Ispares: 129, Number_of_MW_Spectral_Pts: 16, Number_of_P_Levels: 100, Number_of_Rspares: 262, Number_of_Stability_Parameters: 16, Number_of_Surf_Emis_Hinge_Pts: 100)
Coordinates:
    Time                  (Number_of_CrIS_FORs) float64 ...
    Latitude              (Number_of_CrIS_FORs) float32 ...
    Longitude             (Number_of_CrIS_FORs) float32 ...
    Pressure              (Number_of_CrIS_FORs, Number_of_P_Levels) float32 ...
    Effective_Pressure    (Number_of_CrIS_FORs, Number_of_P_Levels) float32 ...
Dimensions without coordinates: Number_of_Cloud_Emis_Hing_Pts, Number_of_Cloud_Layers, Number_of_CrIS_FORs, Number_of_Ispares, Number_of_MW_Spectral_Pts, Number_of_P_Levels, Number_of_Rspares, Number_of_Stability_Parameters, Number_of_Surf_Emis_Hinge_Pts
Data variables:
    quality_information   |S1 ...
    CrIS_FORs             (Number

In [36]:
import xarray as xr

In [37]:
baseURL = 'http://www.esrl.noaa.gov'
catalogURL = '/psd/thredds/dodsC/Datasets/noaa.ersst.v5/sst.mnmean.nc'
sst = xr.open_dataset(baseURL+catalogURL)
sst

<xarray.Dataset>
Dimensions:    (lat: 89, lon: 180, nbnds: 2, time: 1995)
Coordinates:
  * lat        (lat) float32 88.0 86.0 84.0 82.0 80.0 78.0 76.0 74.0 72.0 ...
  * lon        (lon) float32 0.0 2.0 4.0 6.0 8.0 10.0 12.0 14.0 16.0 18.0 ...
  * time       (time) datetime64[ns] 1854-01-01 1854-02-01 1854-03-01 ...
Dimensions without coordinates: nbnds
Data variables:
    time_bnds  (time, nbnds) float64 ...
    sst        (time, lat, lon) float32 ...
Attributes:
    climatology:                     Climatology is based on 1971-2000 SST, X...
    description:                     In situ data: ICOADS2.5 before 2007 and ...
    keywords_vocabulary:             NASA Global Change Master Directory (GCM...
    keywords:                        Earth Science > Oceans > Ocean Temperatu...
    instrument:                      Conventional thermometers
    source_comment:                  SSTs were observed by conventional therm...
    geospatial_lon_min:              -1.0
    geospatial_lon_max