## 5 Importing Standard Earth Science Datasets
## 5.1 Text

In [1]:
import pandas as pd
fname = 'data/campfire-gases-2018-11.csv'
trace_gases = pd.read_csv(fname)

In [2]:
trace_gases.head()

Latitude  Longitude                           Time  H2O_MR_500mb  \
0  39.693913 -120.49820  2018-11-01 10:39:44.183998108      0.001621   
1  39.996113 -121.75796  2018-11-01 10:39:44.383998871      0.001781   
2  39.248516 -120.72343  2018-11-01 10:39:52.183998108      0.001681   
3  39.547660 -121.97622  2018-11-01 10:39:52.383998871      0.001817   
4  38.802532 -120.94534  2018-11-01 10:40:00.184000015      0.001604   

   H2O_MR_850mb  CO_MR_500mb  CO_MR_850mb  O3_MR_500mb  O3_MR_850mb  \
0      0.008410     84.18882   117.011190    46.428890    22.921904   
1      0.004849     77.59622   109.939960    44.728848    21.737068   
2      0.005230     80.73684   114.791985    46.114296    22.632338   
3      0.005295     77.39363   108.182520    44.257423    21.417778   
4      0.004505     82.68274   123.891740    47.121635    22.546751   

   CH4_MR_500mb  CH4_MR_850mb  N2O_MR_500mb  N2O_MR_850mb  CO2_500mb  \
0     1842.4436     1892.8062     318.75995     320.22995  402.26596   
1     1861.1800     1891.7012     318.01180     319.45220  402.76318   
2     1861.7188     1894.3835     319.00397     320.42120  402.35360   
3     1847.3370     1889.8491     318.03134     319.47528  403.03867   
4     1890.4450     1899.3243     319.56244     320.96674  403.35144   

   CO2_850mb                       datetime  
0  402.75560  2018-11-01 10:39:44.183998108  
1  402.89474  2018-11-01 10:39:44.383998871  
2  402.72772  2018-11-01 10:39:52.183998108  
3  403.07166  2018-11-01 10:39:52.383998871  
4  403.11090  2018-11-01 10:40:00.184000015

In [3]:
trace_gases['H2O_MR_500mb']

0      0.001621
1      0.001781
2      0.001681
3      0.001817
4      0.001604
         ...   
486    0.000471
487    0.000466
488    0.000484
489    0.000289
490    0.000273
Name: H2O_MR_500mb, Length: 491, dtype: float64

In [4]:
drops = list(trace_gases.columns[5:])
print(drops)

['CO_MR_500mb', 'CO_MR_850mb', 'O3_MR_500mb', 'O3_MR_850mb', 'CH4_MR_500mb', 'CH4_MR_850mb', 'N2O_MR_500mb', 'N2O_MR_850mb', 'CO2_500mb', 'CO2_850mb', 'datetime']


In [5]:
trace_gases.drop(columns=drops, inplace=True)

In [6]:
trace_gases.head()

Latitude  Longitude                           Time  H2O_MR_500mb  \
0  39.693913 -120.49820  2018-11-01 10:39:44.183998108      0.001621   
1  39.996113 -121.75796  2018-11-01 10:39:44.383998871      0.001781   
2  39.248516 -120.72343  2018-11-01 10:39:52.183998108      0.001681   
3  39.547660 -121.97622  2018-11-01 10:39:52.383998871      0.001817   
4  38.802532 -120.94534  2018-11-01 10:40:00.184000015      0.001604   

   H2O_MR_850mb  
0      0.008410  
1      0.004849  
2      0.005230  
3      0.005295  
4      0.004505

In [7]:
with open('data/campfire-gases-2018-11.csv') as data:
    for row in data:
        print(row)
        column=''
        for character in row:
            if character != ',':
                column=column+character
            else:
                print(column)
                column = ''
        break

Latitude,Longitude,Time,H2O_MR_500mb,H2O_MR_850mb,CO_MR_500mb,CO_MR_850mb,O3_MR_500mb,O3_MR_850mb,CH4_MR_500mb,CH4_MR_850mb,N2O_MR_500mb,N2O_MR_850mb,CO2_500mb,CO2_850mb,datetime

Latitude
Longitude
Time
H2O_MR_500mb
H2O_MR_850mb
CO_MR_500mb
CO_MR_850mb
O3_MR_500mb
O3_MR_850mb
CH4_MR_500mb
CH4_MR_850mb
N2O_MR_500mb
N2O_MR_850mb
CO2_500mb
CO2_850mb


In [8]:
#This could be replaced by something like ' '.join(row.split(','))

with open('data/campfire-gases-2018-11.csv') as data:
    for row in data:
        print(row.split(','))
        break


['Latitude', 'Longitude', 'Time', 'H2O_MR_500mb', 'H2O_MR_850mb', 'CO_MR_500mb', 'CO_MR_850mb', 'O3_MR_500mb', 'O3_MR_850mb', 'CH4_MR_500mb', 'CH4_MR_850mb', 'N2O_MR_500mb', 'N2O_MR_850mb', 'CO2_500mb', 'CO2_850mb', 'datetime\n']


## 5.2 NetCDF

In [9]:
from netCDF4 import Dataset

In [10]:
fname='data/aod/JRR-AOD_v1r1_npp_s201808091955538_e201808091957180_c201808092049460_thinned.nc'
file_id = Dataset(fname)

In [11]:
print(file_id)

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF4 data model, file format HDF5):
    Conventions: CF-1.5
    Metadata_Conventions: CF-1.5, Unidata Dataset Discovery v1.0
    standard_name_vocabulary: CF Standard Name Table (version 17, 24 March 2011)
    project: S-NPP Data Exploitation
    institution: DOC/NOAA/NESDIS/NDE->S-NPP Data Exploitation, NESDIS, NOAA, U.S. Department of Commerce
    naming_authority: gov.noaa.nesdis.nde
    satellite_name: NPP
    instrument_name: VIIRS
    title: JPSS Risk Reduction Unique Aerosol Optical Depth
    summary: Aerosol Optical Depth
    history: VIIRS AOD Version 1.0
    processing_level: NOAA Level 2
    references: 
    id: 7e854908-1172-4d11-ae90-fb768144e6b2
    Metadata_Link: JRR-AOD_v1r1_npp_s201808091955538_e201808091957180_c201808092049460.nc
    start_orbit_number: 35149
    end_orbit_number: 35149
    day_night_data_flag: day
    ascend_descend_data_flag: 0
    time_coverage_start: 2018-08-09T19:55:53Z
    time_coverage_end: 2018

In [12]:
file_id.variables.keys()

dict_keys(['Latitude', 'Longitude', 'AOD550', 'QCAll'])

In [13]:
AOD_550 = file_id.variables['AOD550']
type(AOD_550)

netCDF4._netCDF4.Variable

In [14]:
import numpy as np
AOD_550 = np.array(AOD_550)
AOD_550.shape

(768, 3200)

In [15]:
AOD_550

array([[-999.9, -999.9, -999.9, ..., -999.9, -999.9, -999.9],
       [-999.9, -999.9, -999.9, ..., -999.9, -999.9, -999.9],
       [-999.9, -999.9, -999.9, ..., -999.9, -999.9, -999.9],
       ...,
       [-999.9, -999.9, -999.9, ..., -999.9, -999.9, -999.9],
       [-999.9, -999.9, -999.9, ..., -999.9, -999.9, -999.9],
       [-999.9, -999.9, -999.9, ..., -999.9, -999.9, -999.9]],
      dtype=float32)

In [16]:
avgAOD = AOD_550.mean()
print(avgAOD)

-289.06787


In [17]:
print(file_id.variables['AOD550'])

<class 'netCDF4._netCDF4.Variable'>
float32 AOD550(Rows, Columns)
    _FillValue: -999.9
    long_name: Aerosol optical depth at 550 nm
    units: 1
    valid_range: [-0.05  5.  ]
    coordinates: Longitude Latitude
unlimited dimensions: 
current shape = (768, 3200)
filling on


In [18]:
missing = file_id.variables['AOD550']._FillValue
missing

-999.9

In [19]:
keep_rows = AOD_550 != missing

AOD_550[50:60, 100], keep_rows[50:60, 100]

(array([-9.9990002e+02, -9.9990002e+02,  5.4056549e-01,  6.3157362e-01,
         1.5747026e+00,  5.9736818e-01,  6.2397045e-01,  6.7140901e-01,
         6.5959287e-01,  7.6103389e-01], dtype=float32),
 array([False, False,  True,  True,  True,  True,  True,  True,  True,
         True]))

In [20]:
AOD_550_filtered = AOD_550[keep_rows]
AOD_550_filtered

array([0.06569075, 0.08305545, 0.11872342, ..., 0.14237013, 0.16145205,
       0.14933026], dtype=float32)

In [21]:
# Re-compute the statistics, these values look more reasonable.
avgAOD = AOD_550_filtered.mean()
avgAOD

0.41903266

In [22]:
AOD_550.size, AOD_550_filtered.size

(2457600, 1746384)

In [23]:
AOD_550 = file_id.variables['AOD550'][:,:]
type(AOD_550)

numpy.ma.core.MaskedArray

In [24]:
AOD_550[50:60, 100]

masked_array(data=[--, --, 0.5405654907226562, 0.6315736174583435,
                   1.5747026205062866, 0.5973681807518005,
                   0.6239704489707947, 0.671409010887146,
                   0.659592866897583, 0.7610338926315308],
             mask=[ True,  True, False, False, False, False, False, False,
                   False, False],
       fill_value=-999.9,
            dtype=float32)

In [25]:
avgAOD = AOD_550.mean()
avgAOD

0.41903259105672064

In [26]:
file_id.variables['AOD550'].valid_range

array([-0.05,  5.  ], dtype=float32)

## 5.3 HDF

In [27]:
import h5py

fname = 'data/3B-HHR.MS.MRG.3IMERG.20170827-S120000-E122959.0720.V06B.HDF5' 
file_id = h5py.File(fname, 'r')
file_id

<HDF5 file "3B-HHR.MS.MRG.3IMERG.20170827-S120000-E122959.0720.V06B.HDF5" (mode r)>

In [28]:
list(file_id)

['Grid']

In [29]:
print(list(file_id["Grid"].keys()))

['nv', 'lonv', 'latv', 'time', 'lon', 'lat', 'time_bnds', 'lon_bnds', 'lat_bnds', 'precipitationCal', 'precipitationUncal', 'randomError', 'HQprecipitation', 'HQprecipSource', 'HQobservationTime', 'IRprecipitation', 'IRkalmanFilterWeight', 'probabilityLiquidPrecipitation', 'precipitationQualityIndex']


In [30]:
file_id.visit(print)

Grid
Grid/HQobservationTime
Grid/HQprecipSource
Grid/HQprecipitation
Grid/IRkalmanFilterWeight
Grid/IRprecipitation
Grid/lat
Grid/lat_bnds
Grid/latv
Grid/lon
Grid/lon_bnds
Grid/lonv
Grid/nv
Grid/precipitationCal
Grid/precipitationQualityIndex
Grid/precipitationUncal
Grid/probabilityLiquidPrecipitation
Grid/randomError
Grid/time
Grid/time_bnds


In [31]:
precip = file_id["Grid/precipitationCal"][:,:,:]
precip

array([[[-9999.9, -9999.9, -9999.9, ..., -9999.9,     0. ,     0. ],
        [-9999.9, -9999.9, -9999.9, ..., -9999.9,     0. ,     0. ],
        [-9999.9, -9999.9, -9999.9, ..., -9999.9,     0. ,     0. ],
        ...,
        [-9999.9, -9999.9, -9999.9, ..., -9999.9,     0. ,     0. ],
        [-9999.9, -9999.9, -9999.9, ..., -9999.9,     0. ,     0. ],
        [-9999.9, -9999.9, -9999.9, ..., -9999.9,     0. ,     0. ]]],
      dtype=float32)

In [32]:
print(list(file_id["Grid/precipitationCal"].attrs))

['DimensionNames', 'Units', 'units', 'coordinates', '_FillValue', 'CodeMissingValue', 'DIMENSION_LIST']


In [33]:
missing = file_id["Grid/precipitationCal"].attrs['_FillValue']
missing

-9999.9

In [34]:
PrecipMask = (precip == missing)
precip = np.ma.masked_array(precip, mask=PrecipMask)
precip

masked_array(
  data=[[[--, --, --, ..., --, 0.0, 0.0],
         [--, --, --, ..., --, 0.0, 0.0],
         [--, --, --, ..., --, 0.0, 0.0],
         ...,
         [--, --, --, ..., --, 0.0, 0.0],
         [--, --, --, ..., --, 0.0, 0.0],
         [--, --, --, ..., --, 0.0, 0.0]]],
  mask=[[[ True,  True,  True, ...,  True, False, False],
         [ True,  True,  True, ...,  True, False, False],
         [ True,  True,  True, ...,  True, False, False],
         ...,
         [ True,  True,  True, ...,  True, False, False],
         [ True,  True,  True, ...,  True, False, False],
         [ True,  True,  True, ...,  True, False, False]]],
  fill_value=1e+20,
  dtype=float32)

In [35]:
precip.mean()

0.10843209494915407

## 5.4 GRIB2

In [36]:
import pygrib

In [37]:
filename = 'data/gfsanl_3_20200501_0000_000.grb2'
gfs_grb2 = pygrib.open(filename)
records = [str(grb) for grb in gfs_grb2]

In [38]:
records[12]

'13:Temperature:K (instant):regular_ll:isobaricInPa:level 40 Pa:fcst time 0 hrs:from 202005010000'

In [39]:
temps = gfs_grb2.select(name='Temperature')

In [40]:
temp = gfs_grb2[315]

In [41]:
temps

[13:Temperature:K (instant):regular_ll:isobaricInPa:level 40 Pa:fcst time 0 hrs:from 202005010000,
 17:Temperature:K (instant):regular_ll:isobaricInhPa:level 100 Pa:fcst time 0 hrs:from 202005010000,
 23:Temperature:K (instant):regular_ll:isobaricInhPa:level 200 Pa:fcst time 0 hrs:from 202005010000,
 29:Temperature:K (instant):regular_ll:isobaricInhPa:level 300 Pa:fcst time 0 hrs:from 202005010000,
 35:Temperature:K (instant):regular_ll:isobaricInhPa:level 500 Pa:fcst time 0 hrs:from 202005010000,
 41:Temperature:K (instant):regular_ll:isobaricInhPa:level 700 Pa:fcst time 0 hrs:from 202005010000,
 47:Temperature:K (instant):regular_ll:isobaricInhPa:level 1000 Pa:fcst time 0 hrs:from 202005010000,
 54:Temperature:K (instant):regular_ll:isobaricInhPa:level 1500 Pa:fcst time 0 hrs:from 202005010000,
 58:Temperature:K (instant):regular_ll:isobaricInhPa:level 2000 Pa:fcst time 0 hrs:from 202005010000,
 65:Temperature:K (instant):regular_ll:isobaricInhPa:level 3000 Pa:fcst time 0 hrs:from 20

In [42]:
temp.keys()

['globalDomain',
 'GRIBEditionNumber',
 'tablesVersionLatest',
 'grib2divider',
 'is_efas',
 'angleSubdivisions',
 'missingValue',
 'ieeeFloats',
 'isHindcast',
 'section0Length',
 'identifier',
 'discipline',
 'editionNumber',
 'totalLength',
 'sectionNumber',
 'section1Length',
 'numberOfSection',
 'centre',
 'centreDescription',
 'subCentre',
 'tablesVersion',
 'masterDir',
 'localTablesVersion',
 'significanceOfReferenceTime',
 'year',
 'month',
 'day',
 'hour',
 'minute',
 'second',
 'dataDate',
 'julianDay',
 'dataTime',
 'productionStatusOfProcessedData',
 'typeOfProcessedData',
 'md5Section1',
 'selectStepTemplateInterval',
 'selectStepTemplateInstant',
 'stepType',
 'is_chemical',
 'is_chemical_distfn',
 'is_aerosol',
 'is_aerosol_optical',
 'setCalendarId',
 'deleteCalendarId',
 'is_uerra',
 'sectionNumber',
 'grib2LocalSectionPresent',
 'deleteLocalDefinition',
 'sectionNumber',
 'gridDescriptionSectionPresent',
 'section3Length',
 'numberOfSection',
 'sourceOfGridDefinition

In [43]:
lat = temp.latitudes
lon = temp.longitudes
level = temp.level
units = temp.units
analysis_date = temp.analDate
fcst_time = temp.forecastTime

## 5.5 Importing Data using xarray
### 5.5.1 netCDF

In [44]:
import xarray as xr

In [45]:
fname = 'data/NUCAPS-EDR_v2r0_npp_s201903031848390_e201903031849090_c201903031941100.nc'
nucaps = xr.open_dataset(fname, decode_times=False)
print(nucaps)

<xarray.Dataset>
Dimensions:               (Number_of_Cloud_Emis_Hing_Pts: 100, Number_of_Cloud_Layers: 8, Number_of_CrIS_FORs: 120, Number_of_Ispares: 129, Number_of_MW_Spectral_Pts: 16, Number_of_P_Levels: 100, Number_of_Rspares: 262, Number_of_Stability_Parameters: 16, Number_of_Surf_Emis_Hinge_Pts: 100)
Coordinates:
    Time                  (Number_of_CrIS_FORs) float64 ...
    Latitude              (Number_of_CrIS_FORs) float32 ...
    Longitude             (Number_of_CrIS_FORs) float32 ...
    Pressure              (Number_of_CrIS_FORs, Number_of_P_Levels) float32 ...
    Effective_Pressure    (Number_of_CrIS_FORs, Number_of_P_Levels) float32 ...
Dimensions without coordinates: Number_of_Cloud_Emis_Hing_Pts, Number_of_Cloud_Layers, Number_of_CrIS_FORs, Number_of_Ispares, Number_of_MW_Spectral_Pts, Number_of_P_Levels, Number_of_Rspares, Number_of_Stability_Parameters, Number_of_Surf_Emis_Hinge_Pts
Data variables:
    quality_information   |S1 ...
    CrIS_FORs             (Number

In [46]:
profile = nucaps.sel(Number_of_CrIS_FORs=0)
print(profile)

<xarray.Dataset>
Dimensions:               (Number_of_Cloud_Emis_Hing_Pts: 100, Number_of_Cloud_Layers: 8, Number_of_Ispares: 129, Number_of_MW_Spectral_Pts: 16, Number_of_P_Levels: 100, Number_of_Rspares: 262, Number_of_Stability_Parameters: 16, Number_of_Surf_Emis_Hinge_Pts: 100)
Coordinates:
    Time                  float64 ...
    Latitude              float32 ...
    Longitude             float32 ...
    Pressure              (Number_of_P_Levels) float32 ...
    Effective_Pressure    (Number_of_P_Levels) float32 ...
Dimensions without coordinates: Number_of_Cloud_Emis_Hing_Pts, Number_of_Cloud_Layers, Number_of_Ispares, Number_of_MW_Spectral_Pts, Number_of_P_Levels, Number_of_Rspares, Number_of_Stability_Parameters, Number_of_Surf_Emis_Hinge_Pts
Data variables:
    quality_information   |S1 ...
    CrIS_FORs             float64 ...
    View_Angle            float32 ...
    Satellite_Height      float32 ...
    FG_Mean_CO2           float32 ...
    Mean_CO2              float32 ..

In [47]:
temp_profile = profile.Temperature
print(temp_profile)

<xarray.DataArray 'Temperature' (Number_of_P_Levels: 100)>
array([212.5855 , 218.80322, 225.43922, 232.34381, 239.13559, 248.75534,
       257.70367, 263.4195 , 265.9976 , 266.10553, 262.76913, 258.74844,
       254.02008, 248.83179, 244.12553, 240.88266, 238.28516, 236.50325,
       235.0083 , 233.87831, 232.78593, 231.43639, 229.92056, 228.23976,
       225.89911, 223.36217, 220.73305, 218.01329, 215.30722, 212.58778,
       209.90991, 207.44534, 205.04303, 203.05025, 201.21675, 199.68356,
       198.15318, 196.62808, 195.28139, 194.55951, 194.51022, 195.56819,
       197.32387, 199.23705, 201.13707, 203.09103, 205.10864, 207.17688,
       209.26501, 211.10672, 212.90063, 214.59312, 216.0913 , 217.54628,
       219.06207, 220.60844, 222.29137, 224.17693, 226.35773, 228.5699 ,
       231.0144 , 233.57248, 236.18112, 238.76892, 241.43259, 244.04184,
       246.57971, 249.06012, 251.48575, 253.85817, 256.14236, 258.3448 ,
       260.46893, 262.4812 , 264.4156 , 266.25723, 267.98773, 269

In [48]:
lat, lon = profile.Latitude.item(), profile.Longitude.item()
print(lat, lon)

26.224599838256836 -95.8237075805664


In [49]:
mask = profile.Pressure.round() == 300
gradient = nucaps.sel(Number_of_P_Levels = mask)
print(gradient)

<xarray.Dataset>
Dimensions:               (Number_of_Cloud_Emis_Hing_Pts: 100, Number_of_Cloud_Layers: 8, Number_of_CrIS_FORs: 120, Number_of_Ispares: 129, Number_of_MW_Spectral_Pts: 16, Number_of_P_Levels: 1, Number_of_Rspares: 262, Number_of_Stability_Parameters: 16, Number_of_Surf_Emis_Hinge_Pts: 100)
Coordinates:
    Time                  (Number_of_CrIS_FORs) float64 ...
    Latitude              (Number_of_CrIS_FORs) float32 ...
    Longitude             (Number_of_CrIS_FORs) float32 ...
    Pressure              (Number_of_CrIS_FORs, Number_of_P_Levels) float32 ...
    Effective_Pressure    (Number_of_CrIS_FORs, Number_of_P_Levels) float32 ...
Dimensions without coordinates: Number_of_Cloud_Emis_Hing_Pts, Number_of_Cloud_Layers, Number_of_CrIS_FORs, Number_of_Ispares, Number_of_MW_Spectral_Pts, Number_of_P_Levels, Number_of_Rspares, Number_of_Stability_Parameters, Number_of_Surf_Emis_Hinge_Pts
Data variables:
    quality_information   |S1 ...
    CrIS_FORs             (Number_o

In [50]:
pres_dict = {}
for i, p in enumerate(profile.Pressure):
    if p >= 100:
        pres_dict.update({int(p) : i})

In [51]:
pres_dict[300]

62

In [52]:
mask = (nucaps.Pressure.round() == 300)
nucaps.Temperature.values[mask]

array([236.18112, 236.28352, 236.14589, 236.03069, 235.30072, 235.43655,
       235.23691, 235.25206, 234.86613, 234.80939, 235.1518 , 234.81044,
       235.79163, 235.11952, 235.38934, 234.979  , 234.47533, 235.44267,
       235.13637, 234.21701, 235.14056, 234.45752, 235.30226, 234.43126,
       234.47362, 236.25554, 234.94931, 234.01836, 234.17488, 233.64445,
       235.5862 , 235.8259 , 235.89117, 236.14111, 235.71196, 235.15016,
       234.94038, 234.902  , 234.9427 , 234.2689 , 234.3949 , 234.09862,
       234.49098, 233.86546, 234.41502, 234.55754, 234.95973, 234.78609,
       234.63591, 234.26591, 234.12054, 234.38416, 233.73224, 234.61636,
       234.55391, 237.28278, 231.6181 , 231.47859, 234.13463, 234.2782 ,
       235.2268 , 235.20087, 235.34587, 235.62068, 235.47453, 235.04105,
       234.73286, 234.59726, 234.19395, 234.47183, 233.76808, 234.34087,
       234.70888, 234.22635, 234.51132, 234.33218, 234.08197, 234.48442,
       234.07797, 233.90732, 233.2773 , 233.69025, 

In [53]:
lats = nucaps.Latitude
lons = nucaps.Longitude

### 5.2.2 GRIB2

In [54]:
filter_keys = {'filter_by_keys' : {'typeOfLevel': 'isobaricInhPa', 'name': 'Temperature'}}

In [55]:
filename = 'data/gfsanl_3_20200501_0000_000.grb2'
gfs = xr.open_dataset(filename, engine='cfgrib', backend_kwargs=filter_keys)
print(gfs)

<xarray.Dataset>
Dimensions:        (isobaricInhPa: 33, latitude: 181, longitude: 360)
Coordinates:
    time           datetime64[ns] ...
    step           timedelta64[ns] ...
  * isobaricInhPa  (isobaricInhPa) int32 1000 975 950 925 900 850 ... 7 5 3 2 1
  * latitude       (latitude) float64 90.0 89.0 88.0 87.0 ... -88.0 -89.0 -90.0
  * longitude      (longitude) float64 0.0 1.0 2.0 3.0 ... 357.0 358.0 359.0
    valid_time     datetime64[ns] ...
Data variables:
    t              (isobaricInhPa, latitude, longitude) float32 ...
Attributes:
    GRIB_edition:            2
    GRIB_centre:             kwbc
    GRIB_centreDescription:  US National Weather Service - NCEP 
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             US National Weather Service - NCEP 
    history:                 2021-07-26T15:44:11 GRIB to CDM+CF via cfgrib-0....


In [56]:
filename = 'data/gfsanl_3_20200501_0000_000.grb2'
gfs = xr.open_dataset(filename, engine='cfgrib', backend_kwargs=filter_keys)
print(gfs)

<xarray.Dataset>
Dimensions:        (isobaricInhPa: 33, latitude: 181, longitude: 360)
Coordinates:
    time           datetime64[ns] ...
    step           timedelta64[ns] ...
  * isobaricInhPa  (isobaricInhPa) int32 1000 975 950 925 900 850 ... 7 5 3 2 1
  * latitude       (latitude) float64 90.0 89.0 88.0 87.0 ... -88.0 -89.0 -90.0
  * longitude      (longitude) float64 0.0 1.0 2.0 3.0 ... 357.0 358.0 359.0
    valid_time     datetime64[ns] ...
Data variables:
    t              (isobaricInhPa, latitude, longitude) float32 ...
Attributes:
    GRIB_edition:            2
    GRIB_centre:             kwbc
    GRIB_centreDescription:  US National Weather Service - NCEP 
    GRIB_subCentre:          0
    Conventions:             CF-1.7
    institution:             US National Weather Service - NCEP 
    history:                 2021-07-26T15:44:11 GRIB to CDM+CF via cfgrib-0....


### 5.2.3 Accessing datasets using OpenDAP

In [57]:
baseURL = 'http://www.esrl.noaa.gov'
catalogURL = '/psd/thredds/dodsC/Datasets/noaa.ersst.v5/sst.mnmean.nc'
sst = xr.open_dataset(baseURL+catalogURL)
print(sst)

<xarray.Dataset>
Dimensions:    (lat: 89, lon: 180, nbnds: 2, time: 2010)
Coordinates:
  * lat        (lat) float32 88.0 86.0 84.0 82.0 ... -82.0 -84.0 -86.0 -88.0
  * lon        (lon) float32 0.0 2.0 4.0 6.0 8.0 ... 352.0 354.0 356.0 358.0
  * time       (time) datetime64[ns] 1854-01-01 1854-02-01 ... 2021-06-01
Dimensions without coordinates: nbnds
Data variables:
    time_bnds  (time, nbnds) float64 ...
    sst        (time, lat, lon) float32 ...
Attributes:
    climatology:                     Climatology is based on 1971-2000 SST, X...
    description:                     In situ data: ICOADS2.5 before 2007 and ...
    keywords_vocabulary:             NASA Global Change Master Directory (GCM...
    keywords:                        Earth Science > Oceans > Ocean Temperatu...
    instrument:                      Conventional thermometers
    source_comment:                  SSTs were observed by conventional therm...
    geospatial_lon_min:              -1.0
    geospatial_lon_max: 